export const TYPES = {
	Application: Symbol.for('Application'),
	PrismaService: Symbol.for('PrismaService'),
	IExceptionFilter: Symbol.for('IExceptionFilter'),
	ILogger: Symbol.for('ILogger'),
	IConfigService: Symbol.for('IConfigService'),
	IUsersController: Symbol.for('IUsersController'),
	IUsersService: Symbol.for('IUsersService'),
	IUsersRepository: Symbol.for('IUsersRepository'),
	IAuthController: Symbol.for('IAuthController'),
	IAuthService: Symbol.for('IAuthService'),
	IAuthRepository: Symbol.for('IAuthRepository'),
	JWTService: Symbol.for('JWTService'),
	IModuleService: Symbol.for('IModuleService'),
	IModuleRepository: Symbol.for('IModuleRepository'),
	IModuleController: Symbol.for('IModuleController'),
	ITermRepository: Symbol.for('ITermRepository'),
	ITermService: Symbol.for('ITermService'),
	ITermController: Symbol.for('ITermController'),

	IResetTokenRepository: Symbol.for('IResetTokenRepository'),
	ITokenSender: Symbol.for('ITokenSender'),
};
